### ISSUE TITLE
Is robotware 5.15 supported?

### ISSUE THREAD

**Issue by aaronjauf** [rpiRobotics/abb_motion_program_exec#41]
Hi, do you know if this works with robotware 5.15? It seems like "PC Interface" and "Multitasking" are available in our controller. Thank you

**Comment by johnwason** [comment]
This package uses robot web services which I do not believe is available before version 6. Which robot are you using snd with which institution?

**Comment by aaronjauf** [comment]
Thank you for the quick response. Yes, robot web services are introduced in version 6, so it will not work, thank you. It's an IRB120 we are using at a technical high school.

**Comment by johnwason** [comment]
I think it is possible to update to version 6.x from 5.x on most controllers. Have you contacted ABB?

**Comment by aaronjauf** [comment]
From what I read on various forums, 5.15 cannot be updated to 6.x, only >=5.6 can. I'll try with sockets, as they seem to be supported (similar to https://github.com/robotics/open_abb ). Thank you for your comments.

**Comment by johnwason** [comment]
5.15 is a higher version than 5.6. Software versioning is not interpreted as a normal decimal point.

**Comment by aaronjauf** [comment]
oh, sry, >=5.6x can
