### ISSUE TITLE
Error sending EGM UdpUc message with path correct

### ISSUE THREAD

**Issue by abb939** [rpiRobotics/abb_motion_program_exec#44]
Hello,

I work with RobotStudio 6.08 and EGM. In the simulation environment it works fine with path guidance. But when I use path correction I always get the error:

- 41830, Error sending EGM UdpUc message.

And the robot didn't correct the path as set. Instead, it just executed the original path. I couldn't solve the problem. Could you give me some help?

Look forward to your response.

**Comment by johnwason** [comment]
EGM errors can be hard to diagnose. Based on this error code, my suspicion is that the UDP remote address for EGM has not been configured correctly. With EGM you need to configure the IP address of the computer on the robot controller. The robot controller and computer must be on the same subnet.

See Section 3.3 (page 34) of the manual: https://library.e.abb.com/public/4c9bfa6a4e9542bf9386c87f5377a27f/3HAC073319%20AM%20Externally%20Guided%20Motion%20RW6-en.pdf?x-sign=W42ZwkRuP3q1Dr78NoMTFHI0DdPMmb7ezINcsvqB/Ij7YxK7rdtzREC7RSoHvQJW

**Comment by abb939** [comment]
Thank you for your help.

I have considered this, but it doesn't seem to be the cause, as I managed to implement Position Stream and Position Guidance with the same configuration. In addition, I have tried to change the remote IP address in the robot controller and the IP address of the PC, but I still get the same error.

The first picture is the settings inside the Robotstudio, and the second picture is the configuration of the Ethernet on the PC.
![2](https://github.com/rpiRobotics/abb_motion_program_exec/assets/115632844/c4cbef7d-0066-4acf-bdd4-c1fe59f1fed9)
![1](https://github.com/rpiRobotics/abb_motion_program_exec/assets/115632844/4711ab05-0d4c-4845-bd7a-e8441bbb4824)

**Comment by johnwason** [comment]
What is the IP address of the robot? Is it a different IP address on the same subnet?

**Comment by abb939** [comment]
I only set it up in the software and didn't apply it to the real robot. Need I change the IP address of the controller in the software?

**Comment by johnwason** [comment]
You will need to configure the real robot to have a known ip address that is in the sane subnet as your computer. You then need to configure the udpuc device on the real robot to point to your computer. Make sure you have the correct adapter.

What time zone are you in?

**Comment by abb939** [comment]
Thank you for you advice.

I will follow your advice and try to apply it on the real robot.

In addition, I'm in the East 8 area and there may be some time difference from where you are. I apologize for the inconvenience caused by me.

**Comment by abb939** [comment]
I'm glad to say I have successfully configured the udpuc device on the real robot and the robot properly corrected its path. But I don't understand why it can't be implemented in a simulation environment. Maybe my communication Settings are not completely correct. All in all this is a very satisfactory result.

Thank you for your advice again! They are very useful to me.
