### ISSUE TITLE
support for ABB GoFa robot

### ISSUE THREAD

**Issue by AnirbanSinhaRobotics** [rpiRobotics/abb_motion_program_exec#48]
Does *abb_motion_program_exec* support ABB GoFa 15000 robot? Is there any document available that one follow to setup EGM on OmniCoreC30 controller to use *abb_motion_program_exec*?

Thank you in advance.

**Comment by johnwason** [comment]
Only IRC5 is currently supported.

**Comment by AnirbanSinhaRobotics** [comment]
Ok, thanks. Is there any plan to include OmniCoreC30 controller in the near future?

**Comment by johnwason** [comment]
It should be possible but we do not have any OmniCore robots so it is not a high priority.

**Comment by johnwason** [comment]
Closing as duplicate of #37 for OmniCore support.
